# Auto-generated by Firmgen — DO NOT EDIT.
# Explicit list of firmware sources + include dirs, refreshed before every
# build. Replaces the old file(GLOB ...) (which cached stale results and could
# escape the project). FW_ROOT is set by the including main/CMakeLists.txt.

set(APP_SOURCES
    "${FW_ROOT}/app/app.c"
    "${FW_ROOT}/app/app_tasks.c"
    "${FW_ROOT}/app/state_machine.c"
    "${FW_ROOT}/drivers/adxl355.c"
    "${FW_ROOT}/drivers/inmp441.c"
    "${FW_ROOT}/drivers/modbus_stack.c"
    "${FW_ROOT}/drivers/status_led_ws2812.c"
    "${FW_ROOT}/drivers/thermal_adc.c"
    "${FW_ROOT}/dsp/vibration_metrics.c"
    "${FW_ROOT}/net/mqtt_client_mgr.c"
    "${FW_ROOT}/net/wifi_prov_mgr.c"
    "${FW_ROOT}/utils/helpers/helpers.c"
    "${FW_ROOT}/utils/logger/logger.c"
    "${FW_ROOT}/utils/psram_alloc.c"
    "${FW_ROOT}/utils/ringbuf_psram.c"
)

set(FW_INCLUDE_DIRS
    "${FW_ROOT}"
    "${FW_ROOT}/app"
    "${FW_ROOT}/configs"
    "${FW_ROOT}/drivers"
    "${FW_ROOT}/dsp"
    "${FW_ROOT}/net"
    "${FW_ROOT}/utils"
    "${FW_ROOT}/utils/helpers"
    "${FW_ROOT}/utils/logger"
)
